import { ExtractionResult } from './extraction.schema';

/** Deterministic mock receipts keyed by `fixture:<id>` buffer prefix (eval harness). */
export const MOCK_SCENARIOS: Record<string, ExtractionResult> = {
  'mock-safeway-01': {
    store: { name: 'Safeway', address: '2417 Tongass Ave' },
    purchasedAt: null,
    paymentMethod: 'VISA',
    currency: 'USD',
    subtotalCents: 1147,
    taxCents: 0,
    totalCents: 1147,
    confidence: 0.92,
    lines: [
      {
        lineNumber: 1,
        rawText: 'GV MLK WHL 1GA',
        quantity: 1,
        unitPriceCents: 549,
        extendedCents: 549,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'dairy',
      },
      {
        lineNumber: 2,
        rawText: 'BANANAS',
        quantity: 2.14,
        unitPriceCents: 79,
        extendedCents: 169,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'produce',
      },
      {
        lineNumber: 3,
        rawText: 'EGGS LG 12CT',
        quantity: 1,
        unitPriceCents: 429,
        extendedCents: 429,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'dairy',
      },
    ],
  },
  'mock-superbear-01': {
    store: { name: 'Super Bear', address: '2415 Tongass Ave' },
    purchasedAt: null,
    paymentMethod: 'CASH',
    currency: 'USD',
    subtotalCents: 892,
    taxCents: 0,
    totalCents: 892,
    confidence: 0.9,
    lines: [
      {
        lineNumber: 1,
        rawText: 'BREAD WHT',
        quantity: 1,
        unitPriceCents: 349,
        extendedCents: 349,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'bakery',
      },
      {
        lineNumber: 2,
        rawText: 'PB 16OZ',
        quantity: 1,
        unitPriceCents: 543,
        extendedCents: 543,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'pantry',
      },
    ],
  },
  'mock-als-01': {
    store: { name: "Al's Alaska Meat", address: '2557 Tongass Ave' },
    purchasedAt: null,
    paymentMethod: 'DEBIT',
    currency: 'USD',
    subtotalCents: 1897,
    taxCents: 0,
    totalCents: 1897,
    confidence: 0.91,
    lines: [
      {
        lineNumber: 1,
        rawText: 'GRND BEEF 80/20',
        quantity: 2.05,
        unitPriceCents: 599,
        extendedCents: 1228,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'meat',
      },
      {
        lineNumber: 2,
        rawText: 'CHKN BRST',
        quantity: 1.12,
        unitPriceCents: 597,
        extendedCents: 669,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'meat',
      },
    ],
  },
  'mock-costco-01': {
    store: { name: 'Costco', address: '50 Denali St' },
    purchasedAt: null,
    paymentMethod: 'VISA',
    currency: 'USD',
    subtotalCents: 4598,
    taxCents: 0,
    totalCents: 4598,
    confidence: 0.93,
    lines: [
      {
        lineNumber: 1,
        rawText: 'KS PAPER TOWEL 6PK',
        quantity: 1,
        unitPriceCents: 1899,
        extendedCents: 1899,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'household',
      },
      {
        lineNumber: 2,
        rawText: 'KS TP 12RL',
        quantity: 1,
        unitPriceCents: 1699,
        extendedCents: 1699,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'household',
      },
      {
        lineNumber: 3,
        rawText: 'BANANAS',
        quantity: 3.2,
        unitPriceCents: 69,
        extendedCents: 221,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'produce',
      },
      {
        lineNumber: 4,
        rawText: 'MILK 1GAL',
        quantity: 1,
        unitPriceCents: 779,
        extendedCents: 779,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'dairy',
      },
    ],
  },
  'mock-taxed-01': {
    store: { name: 'Walmart', address: '2400 Tongass Ave' },
    purchasedAt: null,
    paymentMethod: 'VISA',
    currency: 'USD',
    subtotalCents: 1000,
    taxCents: 60,
    totalCents: 1060,
    confidence: 0.88,
    lines: [
      {
        lineNumber: 1,
        rawText: 'DISH SOAP 24OZ',
        quantity: 1,
        unitPriceCents: 449,
        extendedCents: 449,
        discountCents: 0,
        isTaxable: true,
        isRefund: false,
        guessedCategory: 'household',
      },
      {
        lineNumber: 2,
        rawText: 'LAUNDRY DET 100OZ',
        quantity: 1,
        unitPriceCents: 551,
        extendedCents: 551,
        discountCents: 0,
        isTaxable: true,
        isRefund: false,
        guessedCategory: 'household',
      },
    ],
  },
  'mock-discount-01': {
    store: { name: 'Safeway', address: '2417 Tongass Ave' },
    purchasedAt: null,
    paymentMethod: 'VISA',
    currency: 'USD',
    subtotalCents: 650,
    taxCents: 0,
    totalCents: 650,
    confidence: 0.89,
    lines: [
      {
        lineNumber: 1,
        rawText: 'COFFEE 12OZ',
        quantity: 1,
        unitPriceCents: 899,
        extendedCents: 899,
        discountCents: 249,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'beverages',
      },
    ],
  },
  'mock-weighable-01': {
    store: { name: 'Super Bear', address: '2415 Tongass Ave' },
    purchasedAt: null,
    paymentMethod: 'DEBIT',
    currency: 'USD',
    subtotalCents: 512,
    taxCents: 0,
    totalCents: 512,
    confidence: 0.9,
    lines: [
      {
        lineNumber: 1,
        rawText: 'BANANAS',
        quantity: 1.85,
        unitPriceCents: 89,
        extendedCents: 165,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'produce',
      },
      {
        lineNumber: 2,
        rawText: 'ONIONS YLW 3LB',
        quantity: 1,
        unitPriceCents: 347,
        extendedCents: 347,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'produce',
      },
    ],
  },
  'mock-short-01': {
    store: { name: 'Three Bears', address: '2417 Tongass Ave' },
    purchasedAt: null,
    paymentMethod: 'CASH',
    currency: 'USD',
    subtotalCents: 299,
    taxCents: 0,
    totalCents: 299,
    confidence: 0.95,
    lines: [
      {
        lineNumber: 1,
        rawText: 'GREEK YOG 32OZ',
        quantity: 1,
        unitPriceCents: 299,
        extendedCents: 299,
        discountCents: 0,
        isTaxable: false,
        isRefund: false,
        guessedCategory: 'dairy',
      },
    ],
  },
};
